### PR TITLE
Firefox role (Sandbox) + add mkdocs-material privacy plugin

### PR DESCRIPTION
**Pull request by keldian**
Fully previewed and tested using the Insiders edition.

- [x] App documentation page created
- [x] markdownlint reports no errors on edited page(s) - use <https://dlaa.me/markdownlint/> if your IDE does not have this built in
- [x] Reference added in `docs/sandbox/index.md`
- [x] Reference added in `mkdocs.yml` nav menu
- [x] Healthcheck sample added in `docs/advanced/healthchecks.md`

Also, `extra.css` got linted as I added some things.

### CODE REVIEW

**Comment by saltydk** [comment]
The privacy plugin addition adds far more than what you wanted to add it for. Even if you left out the other settings most of them default to true.

**Comment by keldian** [comment]
Oof, that went over my head.

Looks like it's just [assets](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.assets) that would have to be overridden right? To my understanding [concurrency](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.concurrency) and all other asset related options depend on that one being enabled.

**Comment by saltydk** [comment]
Yeah, by default it downloads all external assets and bundles them in the build. All of which probably slows the build time locally, this can be fixed with an ENV but then everyone would have to know about that toggle. I'm not saying not to use it but we should consider if it is worth the potential trouble seeing as this feature is experimental and already mentions the issue with the font download on the linked page.

**Comment by keldian** [comment]
Right then, I'm setting `assets` to false. If you guys decide we don't want `privacy` at all, I guess you can discard the plugin commits.

**Comment by saltydk** [comment]
I'll let chaz decide on it as he handles most of the docs these days, just sharing my thoughts on it.

**Comment by saltydk** [comment]
Can you move this PR to traefik3?

**Comment by keldian** [comment]
> Can you move this PR to traefik3?

Done. Want me to do the same with https://github.com/saltyorg/docs/pull/213?

**Comment by saltydk** [comment]
> > Can you move this PR to traefik3?
> 
> Done. Want me to do the same with #213?

Sure.

**Comment by keldian** [comment]
Done.

**Comment by saltydk** [comment]
main branch has been archived.

**Pull request closed without merging**
