### PR TITLE
Update SS & correct api info

### PR DESCRIPTION
**Pull request by RaneyDazed**
# Please describe the purpose of this Pull Request.

Ensure correct API Key configuration for Sabnzbd connection in Radarr
and Sonarr settings, corrected sonarr category, added SS of both radarr and sonarr.

### CODE REVIEW

**Comment by RaneyDazed** [comment]
Might be a good idea to link to sab docs too? Since I removed the 2 lines that linked to it to reference the user/pass?

**Comment by RaneyDazed** [comment]
omg. I'll need to redo that. I think it renumbered the radarr page

**Comment by RaneyDazed** [comment]
I'll take different screen shots with user and pass

**Review by chazlarson — CHANGES_REQUESTED** [review]
There's no radarr page.

**Pull request merged**
