### PR TITLE
Update commands

### PR DESCRIPTION
**Pull request by Elbulus**
Updating the install commands for sandbox apps

### CODE REVIEW

**Review by chazlarson — APPROVED** [review]

**Comment by keldian** [comment]
https://github.com/saltyorg/Sandbox/commit/3e553073114fa78aec1912e0d48358dbb26e6b63
A teensy bit more work needed.

**Comment by owine** [comment]
Sorry, I missed this PR and made a bunch of these changes manually. Can you please rebase as I'd like to merge a few others you have in here?

**Comment by Elbulus** [comment]
> Sorry, I missed this PR and made a bunch of these changes manually. Can you please rebase as I'd like to merge a few others you have in here?

Sure i'll have a look at sorting that tomorrow.

**Comment by Elbulus** [comment]
Pretty sure i've caught them all now.

**Pull request merged**
