### PR TITLE
Update logarr.md

### PR DESCRIPTION
**Pull request by rbax82**
is not behind any sort of authentication

Please describe the purpose of this Pull Request.

For new Sandbox app/role documentation, please confirm you have completed the following tasks:

- [] App documentation page created
- [] markdownlint reports no errors on edited page(s) - use <https://dlaa.me/markdownlint/> if your IDE does not have this built in
- [] Reference added in `docs/sandbox/index.md`
- [] Reference added in `mkdocs.yml` nav menu

To confirm you have read the above, please remove this line.

### CODE REVIEW

**Comment by rbax82** [comment]
go

**Comment by maximuskowalski** [comment]
It's been a while but I think authentication is one of the things you are meant to set up when doing the initial config. Have you tested this PR?

**Comment by maximuskowalski** [comment]
Ah - docs! Sorry, thought it was Sandbox 🤣

**Comment by saltydk** [comment]
Just add authelia in Sandbox.

**Pull request closed without merging**
