### PR TITLE
Remove _ from domains

### PR DESCRIPTION
**Pull request by benwaco**
I don't think these are necessary, makes it look weird.

### CODE REVIEW

**Comment by RaneyDazed** [comment]
every one of the roles also has them in them as well btw :p 
image

**Comment by chazlarson** [comment]
That's there because `_yourdomain.com_` is a placeholder for the user's domain.  In my opinion, if those change to https://whatever.yourdomain.com then they might light up as clickable links and people will come to the discord to complain that it won't load.

**Comment by maximuskowalski** [comment]
> I might argue that they are _intended_ to look weird to call the user's attention to that as something they need to change.

Might need to make them even more weird really given it still seems to get copied and pasted.

**Comment by benwaco** [comment]
I think example.com serves a better placeholder for it, but that's just me. Feel free to close.

**Comment by keldian** [comment]
> > I might argue that they are _intended_ to look weird to call the user's attention to that as something they need to change.
> 
> Might need to make them even more weird really given it still seems to get copied and pasted.

How about chevrons? 
```
https://subdomain.<yourdomain.com> 
```

**Comment by maximuskowalski** [comment]
Nobody seems to have offered any more opinions so I am just going to close this one.

**Pull request closed without merging**
