### PR TITLE
Sandbox-Calibre : specify the default username

### PR DESCRIPTION
**Pull request by grostim**
[See this issue](https://github.com/saltyorg/Sandbox/issues/42)

### CODE REVIEW

**Comment by chazlarson** [comment]
Is a password actually set?

**Comment by grostim** [comment]
> Is a password actually set?

Yes. The default user.pass as defined in settings.yaml

**Comment by saltydk** [comment]
Yes. Default user is abc per https://docs.linuxserver.io/images/docker-calibre and password is set here https://github.com/saltyorg/Sandbox/blob/476b2dbeef07bcf6e24397faf1cf1f0085dc978b/roles/calibre/defaults/main.yml#L89

**Comment by grostim** [comment]
However, for a more consistent exeperience across saltbox, it would make sense to disable authentication in calibre and to rely on authelia authentication.

**Comment by saltydk** [comment]
Take that up with the Sandbox maintainers :p

**Comment by chazlarson** [comment]
Okey doke; I thought I'd installed it and there was a no password.  Probably just a dream.

**Comment by saltydk** [comment]
> Okey doke; I thought I'd installed it and there was no password. Probably just a dream.

Maybe we added it at a later date, I don't recall.

**Pull request merged**
