### PR TITLE
Update sarotate.md

### PR DESCRIPTION
**Pull request by RaneyDazed**
Updated sarotate.md page, added to mkdocs, added brief explanation for service account actions.

- [x] App documentation page updated
- [x] Reference added in `mkdocs.yml`

### CODE REVIEW

**Comment by RaneyDazed** [comment]
Whomever takes a look at it, lmk if I should move the SA example before `sb install sandbox-sarotate` or if its fine?

**Comment by maximuskowalski** [comment]
Not sure if it might be worth filling some details in as an example in the rest of the config file.

**Comment by RaneyDazed** [comment]
I'll try to get back to this today at some point. :)

**Comment by RaneyDazed** [comment]
I guess I’ll need to get back to this huh? 😂 people are asking questions!

**Pull request closed without merging**
