### PR TITLE
Update to kcptun_client.md

### PR DESCRIPTION
**Pull request by RaneyDazed**
The name of the role was APPNAME. Corrected the name.

### CODE REVIEW

**Comment by saltydk** [comment]
Correct away but what is with the weird capitalization?

**Comment by RaneyDazed** [comment]
Sorry lol, I saw KCP was in caps in the description

**Comment by RaneyDazed** [comment]
I was just coming back to add caps to the top of the doc too

**Comment by saltydk** [comment]
kcptun isn't caps on their own github page though.

**Comment by RaneyDazed** [comment]
Oh fair enough.

**Comment by RaneyDazed** [comment]
removed caps on both PRs.

**Comment by maximuskowalski** [comment]
Thanks RaneyDazed - APPNAME was me :) Sorry chaps.

**Comment by RaneyDazed** [comment]
> Thanks RaneyDazed - APPNAME was me :) Sorry chaps.

ha I was curious who had left that in there.

**Pull request merged**
